import type { KPIData, FunnelStep, SalesByHour, PaymentMethod, Campaign } from '@/types'

export const mockKPIs: KPIData = {
  investimento: 5847.30,
  custoVendaMeta: 19.46,
  custoVendaBanco: 17.82,
  vendasBanco: 309,
  lucro: 8253.00,
  roas: 2.41,
}

export const mockFunnel: FunnelStep[] = [
  { label: 'Cliques', value: 12712 },
  { label: 'Landing Page Views', value: 11872, delta: -6.6 },
  { label: 'Iniciar Compra', value: 2887, delta: -75.7 },
  { label: 'Vendas', value: 609, money: 'R$ 13.535', delta: -78.9 },
  { label: 'OB [Gravação] Claude Code', value: 300, money: 'R$ 14.108', delta: -50.7 },
  { label: 'Mesa de Comando – Zoom', value: 8, money: 'R$ 3.176', delta: -97.3 },
]

export const mockSalesByHour: SalesByHour[] = [
  { hora: '00h', vendas: 4 },
  { hora: '01h', vendas: 2 },
  { hora: '02h', vendas: 1 },
  { hora: '03h', vendas: 0 },
  { hora: '04h', vendas: 1 },
  { hora: '05h', vendas: 3 },
  { hora: '06h', vendas: 8 },
  { hora: '07h', vendas: 14 },
  { hora: '08h', vendas: 21 },
  { hora: '09h', vendas: 28 },
  { hora: '10h', vendas: 35 },
  { hora: '11h', vendas: 42 },
  { hora: '12h', vendas: 38 },
  { hora: '13h', vendas: 31 },
  { hora: '14h', vendas: 29 },
  { hora: '15h', vendas: 33 },
  { hora: '16h', vendas: 27 },
  { hora: '17h', vendas: 24 },
  { hora: '18h', vendas: 19 },
  { hora: '19h', vendas: 16 },
  { hora: '20h', vendas: 22 },
  { hora: '21h', vendas: 18 },
  { hora: '22h', vendas: 12 },
  { hora: '23h', vendas: 7 },
]

export const mockPaymentMethods: PaymentMethod[] = [
  { name: 'Pix', value: 65, color: '#FF6B00' },
  { name: 'Cartão de Crédito', value: 28, color: '#FF8C3A' },
  { name: 'Boleto', value: 7, color: '#CC5500' },
]

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp_001',
    name: 'OB | Claude Code Para Prestadores Digitais | Conversões | Brasil | LAL 1-2% Compradores 90d',
    status: 'ACTIVE',
    budget: 1500,
    budgetType: 'CBO',
    metrics: {
      cpm: 18.42,
      impressoes: 284710,
      cliques: 5234,
      alcance: 198430,
      vendasMeta: 124,
      vendasBanco: 131,
      custoVenda: 18.92,
      lucro: 3842.00,
      roas: 2.61,
      investimento: 2345.80,
    },
    adSets: [
      {
        id: 'adset_001',
        name: 'LAL 1-2% Compradores 90d | 25-44 | Brasil',
        status: 'ACTIVE',
        budget: 0,
        budgetType: 'daily',
        metrics: {
          cpm: 17.80,
          impressoes: 142300,
          cliques: 2680,
          alcance: 98200,
          vendasMeta: 62,
          vendasBanco: 65,
          custoVenda: 18.20,
          lucro: 1921.00,
          roas: 2.65,
          investimento: 1128.40,
        },
        ads: [
          {
            id: 'ad_001',
            name: 'VSL Principal | Claude Code | Depoimento João | v3',
            status: 'ACTIVE',
            instagramPostUrl: 'https://www.instagram.com/p/CxAbCdEfGhI/',
            metrics: {
              cpm: 16.90,
              impressoes: 82400,
              cliques: 1560,
              alcance: 57300,
              vendasMeta: 38,
              vendasBanco: 40,
              custoVenda: 17.30,
              lucro: 1182.00,
              roas: 2.75,
              investimento: 657.20,
            },
          },
          {
            id: 'ad_002',
            name: 'VSL Alternativo | Claude Code | Transformação em 30 dias | v1',
            status: 'PAUSED',
            instagramPostUrl: 'https://www.instagram.com/p/CyAbCdEfGhI/',
            metrics: {
              cpm: 19.20,
              impressoes: 59900,
              cliques: 1120,
              alcance: 40900,
              vendasMeta: 24,
              vendasBanco: 25,
              custoVenda: 19.64,
              lucro: 739.00,
              roas: 2.50,
              investimento: 471.20,
            },
          },
        ],
      },
      {
        id: 'adset_002',
        name: 'LAL 2-5% Compradores 90d | 28-50 | Brasil',
        status: 'ACTIVE',
        budget: 0,
        budgetType: 'daily',
        metrics: {
          cpm: 19.20,
          impressoes: 142410,
          cliques: 2554,
          alcance: 100230,
          vendasMeta: 62,
          vendasBanco: 66,
          custoVenda: 19.62,
          lucro: 1921.00,
          roas: 2.57,
          investimento: 1217.40,
        },
        ads: [
          {
            id: 'ad_003',
            name: 'VSL Principal | Claude Code | Depoimento Maria | v2',
            status: 'ACTIVE',
            instagramPostUrl: 'https://www.instagram.com/p/CzAbCdEfGhI/',
            metrics: {
              cpm: 19.20,
              impressoes: 142410,
              cliques: 2554,
              alcance: 100230,
              vendasMeta: 62,
              vendasBanco: 66,
              custoVenda: 19.62,
              lucro: 1921.00,
              roas: 2.57,
              investimento: 1217.40,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'camp_002',
    name: 'OB | Mesa de Comando | Remarketing | Visitaram LP + Iniciaram Compra | Últimos 14d',
    status: 'ACTIVE',
    budget: 300,
    budgetType: 'CBO',
    metrics: {
      cpm: 22.14,
      impressoes: 98400,
      cliques: 1842,
      alcance: 67300,
      vendasMeta: 48,
      vendasBanco: 52,
      custoVenda: 15.43,
      lucro: 2891.00,
      roas: 3.12,
      investimento: 742.40,
    },
    adSets: [
      {
        id: 'adset_003',
        name: 'Remarketing | Visitaram LP | 1-7d | Excluir Compradores',
        status: 'ACTIVE',
        budget: 0,
        budgetType: 'daily',
        metrics: {
          cpm: 21.50,
          impressoes: 52100,
          cliques: 980,
          alcance: 35200,
          vendasMeta: 25,
          vendasBanco: 27,
          custoVenda: 14.80,
          lucro: 1521.00,
          roas: 3.25,
          investimento: 392.20,
        },
        ads: [
          {
            id: 'ad_004',
            name: 'Retargeting | Urgência | "Você viu mas não entrou" | v2',
            status: 'ACTIVE',
            instagramPostUrl: 'https://www.instagram.com/p/DaAbCdEfGhI/',
            metrics: {
              cpm: 21.50,
              impressoes: 52100,
              cliques: 980,
              alcance: 35200,
              vendasMeta: 25,
              vendasBanco: 27,
              custoVenda: 14.80,
              lucro: 1521.00,
              roas: 3.25,
              investimento: 392.20,
            },
          },
        ],
      },
      {
        id: 'adset_004',
        name: 'Remarketing | Iniciaram Compra | 1-3d | Excluir Compradores',
        status: 'ACTIVE',
        budget: 0,
        budgetType: 'daily',
        metrics: {
          cpm: 23.10,
          impressoes: 46300,
          cliques: 862,
          alcance: 32100,
          vendasMeta: 23,
          vendasBanco: 25,
          custoVenda: 15.21,
          lucro: 1370.00,
          roas: 2.97,
          investimento: 350.20,
        },
        ads: [
          {
            id: 'ad_005',
            name: 'Retargeting | Carrinho Abandonado | Oferta + Bônus | v1',
            status: 'ACTIVE',
            instagramPostUrl: 'https://www.instagram.com/p/DbAbCdEfGhI/',
            metrics: {
              cpm: 23.10,
              impressoes: 46300,
              cliques: 862,
              alcance: 32100,
              vendasMeta: 23,
              vendasBanco: 25,
              custoVenda: 15.21,
              lucro: 1370.00,
              roas: 2.97,
              investimento: 350.20,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'camp_003',
    name: 'OB | Claude Code | Interesses Frios | Tecnologia + Empreendedorismo + Marketing Digital | Brasil | 25-55',
    status: 'PAUSED',
    budgetType: 'ABO',
    metrics: {
      cpm: 31.20,
      impressoes: 89420,
      cliques: 1820,
      alcance: 62100,
      vendasMeta: 38,
      vendasBanco: 40,
      custoVenda: 27.83,
      lucro: 920.00,
      roas: 1.34,
      investimento: 1055.40,
    },
    adSets: [
      {
        id: 'adset_005',
        name: 'Interesse | Tecnologia | 25-45 | Brasil | R$ 150/dia',
        status: 'PAUSED',
        budget: 150,
        budgetType: 'daily',
        metrics: {
          cpm: 29.80,
          impressoes: 45300,
          cliques: 920,
          alcance: 31400,
          vendasMeta: 19,
          vendasBanco: 20,
          custoVenda: 26.50,
          lucro: 480.00,
          roas: 1.38,
          investimento: 503.20,
        },
        ads: [
          {
            id: 'ad_006',
            name: 'Cold | Imagem Estática | "Automatize sua agência com IA" | v1',
            status: 'PAUSED',
            instagramPostUrl: 'https://www.instagram.com/p/DcAbCdEfGhI/',
            metrics: {
              cpm: 29.80,
              impressoes: 45300,
              cliques: 920,
              alcance: 31400,
              vendasMeta: 19,
              vendasBanco: 20,
              custoVenda: 26.50,
              lucro: 480.00,
              roas: 1.38,
              investimento: 503.20,
            },
          },
        ],
      },
      {
        id: 'adset_006',
        name: 'Interesse | Marketing Digital | 30-55 | Brasil | R$ 150/dia',
        status: 'PAUSED',
        budget: 150,
        budgetType: 'daily',
        metrics: {
          cpm: 33.10,
          impressoes: 44120,
          cliques: 900,
          alcance: 30700,
          vendasMeta: 19,
          vendasBanco: 20,
          custoVenda: 29.20,
          lucro: 440.00,
          roas: 1.30,
          investimento: 552.20,
        },
        ads: [
          {
            id: 'ad_007',
            name: 'Cold | Vídeo Curto 15s | "De 8h no computador para 2h com IA" | v3',
            status: 'PAUSED',
            instagramPostUrl: 'https://www.instagram.com/p/DdAbCdEfGhI/',
            metrics: {
              cpm: 33.10,
              impressoes: 44120,
              cliques: 900,
              alcance: 30700,
              vendasMeta: 19,
              vendasBanco: 20,
              custoVenda: 29.20,
              lucro: 440.00,
              roas: 1.30,
              investimento: 552.20,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'camp_004',
    name: 'OB | Claude Code Para Prestadores | Interesses | Programação + SaaS + Automação | Sul + Sudeste | 22-40',
    status: 'ACTIVE',
    budget: 500,
    budgetType: 'CBO',
    metrics: {
      cpm: 24.30,
      impressoes: 67800,
      cliques: 1380,
      alcance: 47200,
      vendasMeta: 47,
      vendasBanco: 50,
      custoVenda: 21.40,
      lucro: 1400.00,
      roas: 2.08,
      investimento: 1070.00,
    },
    adSets: [
      {
        id: 'adset_007',
        name: 'Interesses | Programação + SaaS | Sul + Sudeste | 22-35',
        status: 'ACTIVE',
        budget: 0,
        budgetType: 'daily',
        metrics: {
          cpm: 24.30,
          impressoes: 67800,
          cliques: 1380,
          alcance: 47200,
          vendasMeta: 47,
          vendasBanco: 50,
          custoVenda: 21.40,
          lucro: 1400.00,
          roas: 2.08,
          investimento: 1070.00,
        },
        ads: [
          {
            id: 'ad_008',
            name: 'VSL | Dev Freelancer | "Tripliquei meu faturamento automatizando entregas" | v1',
            status: 'ACTIVE',
            instagramPostUrl: 'https://www.instagram.com/p/DeAbCdEfGhI/',
            metrics: {
              cpm: 24.30,
              impressoes: 67800,
              cliques: 1380,
              alcance: 47200,
              vendasMeta: 47,
              vendasBanco: 50,
              custoVenda: 21.40,
              lucro: 1400.00,
              roas: 2.08,
              investimento: 1070.00,
            },
          },
        ],
      },
    ],
  },
]
